#!/usr/bin/env bash
# Installs NPM dependencies, starts Redis, and runs the bot.
set -x
prog_dir=$(realpath $(dirname "$0"))
install_dir="{{ pillar.valorant_discord_bot.install_dir }}"

function die() {
    echo "Error: $@" >&2
    exit 1
}

function check() {
    if [ "$@" -ne 0 ]; then
	   die "$@"
    fi
}

# Change to bot directory
cd "$install_dir"
check "Failed to change to bot directory"

# Install NPM depdencies
npm install
check "Failed to install NPM dependencies"

# Start Redis
redis_status=$("$install_dir/redis" status)
check "Failed to get Redis status"

if [ "$redis_status" -ne "running" ]; then
    "$install_dir/redis" start
    check "Failed to start Redis"
fi

# Start bot
exec npm start
check "Failed to start bot server"
