#!/bin/sh

[ -f ./conf ] && . ./conf

: ${WRKDIR:=/var/lib/prometheus}

cd "${WRKDIR}"

exec chpst -u {{ pillar.prometheus.user }}:{{ pillar.prometheus.group }} prometheus --config.file=/etc/prometheus/prometheus.yml $ARGS
