#!/bin/sh

[ -f ./conf ] && . ./conf

: ${WRKDIR:=/var/lib/prometheus}

cd "${WRKDIR}"

exec chpst -u {{ pillar.prometheus.user }}:{{ pillar.prometheus.group }} prometheus \
	--config.file={{ pillar.prometheus.config_file }} \
	--web.listen-address="{{ pillar.prometheus.local_address }}" \
	--storage.tsdb.retention.size "2GB" \
	--web.enable-admin-api 2>&1
