#!/usr/bin/env bash
#?
# log-service - Write stdin to socklog
#
# USAGE
#
#	log-service
#
# BEHAVIOR
#
# 	Determines the name of the service based on the directory the script
#	is symlinked into.
#
#?

# {{{1 Exit on any error
set -e

# {{{1 Configuration
socklog_dir=/var/log/socklog

# {{{1 Determine name of service based on directory
#prog_dir=$(realpath $(dirname "$0"))

# {{{2 Check if running in runit dir
#if [[ ! "$prog_dir" =~ ^/etc/sv/.*/log$ ]]; then
#	echo "Error: not running in runit service log directory, running in \"$prog_dir\"" > svlogd -ttt "$socklog_dir/log-service"
#	exit 1
#fi

#name=$(echo "$prog_dir" | awk -F '/' '{ print $4 }')
#if [[ "$?" != "0" ]]; then
#	echo "Error: Failed to determine service name from directory: \"$prog_dir\"" > svlogd -ttt "$socklog_dir/log-service"
#	exit 1
#fi

# Run svlogd
#exec svlogd -ttt "$socklog_dir/$name"
exec svlogd -ttt "$socklog_dir/everything"
