#!/usr/bin/env bash
exec chpst -u {{ pillar.factorio.user.name}}:{{ pillar.factorio.group.name}}:docker docker run \
	-it \
	--rm \
	--name {{ pillar.factorio.docker_container_name }} \
	--net host \
	-p {{ pillar.factorio.ports.game }}:{{ pillar.factorio.ports.game }}/udp \
	-p {{ pillar.factorio.ports.rcon }}:{{ pillar.factorio.ports.rcon }}/tcp \
	-v {{ pillar.factorio.directory }}:/factorio \
	{{ pillar.factorio.docker_image }}
