apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factorio
labels:
  - pairs:
      project: factorio
      component: server
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - name: server-config
    envs:
      - conf/server-config.env

secretGenerator:
  - name: server-secret
    envs:
      - conf/server-secret.env
    files:
      - conf/server-rconpw.txt

resources:
  - resources/namespace.yaml
  - resources/statefulset.yaml
  # Comment out service when not in use so don't have to pay for LB
  #- resources/service.yaml

replicas:
  - name: factorio
    count: 0
