#!/usr/bin/env bash
#?
# check-log-service-injected - Checks if the log service is injected
#
# USAGE
#
#	check-log-service-injected [SVC]
#
# ARGUMENTS
#
#	SVC    (Optional) Service to check, if not provided checks all services
#
# BEHAVIOR
#
#	Checks to see if a service (or all services if SVC argument not 
#	provided) is sending logs to syslog with vlogger.
#
# 	If the log service(s) is setup correctly exits with code 0. 
# 	Otherwise 1.
#
#?

# {{{1 Exit on any error
set -e

# {{{1 Configuration
log_service_install_f=$(which vlogger)
if [[ "$?" != "0" ]]; then
	echo "Error: Failed to find vlogger script location" >&2
	exit 1
fi

# {{{1 Arguments
svc_arg="$1"

# {{{1 Get name of service(s) to check
services=()

if [ ! -z "$svc_arg" ]; then # If SVC argument given
	services+=("$svc_arg")
else # No SVC specified, check all
	services=("$(ls /var/service)")
fi

# {{{1 Check
not_injected=""

echo "############"
echo "# Checking #"
echo "############"

echo "service(s): $services"

for svc in $services; do
	echo "===== Checking $svc"

	# {{{2 Check if we should ignore service
	if [[ "$svc" =~ ^(acpid|agetty.*|udevd|uuidd)$ ]]; then
		echo "Ignoring"
		continue
	fi

	# {{{2 Service files and directories
	svc_dir="/var/service/$svc"
	svc_log_dir="$svc_dir/log"
	svc_log_run_f="$svc_log_dir/run"

	# {{{2 Check if an existing log/run file exists
	if [ -e "$svc_log_run_f" ]; then
		# {{{3 Check if existing log/run file is log-service script
		actual_path=$(readlink -f "$svc_log_run_f")
		if [[ "$?" != "0" ]]; then
			echo "Error: Failed to readlink for $svc_log_run_f" >&2
			exit 1
		fi

		if [[ "$actual_path" == "$log_service_install_f" ]]; then # If log-service already injected OK
			echo "OK"
			continue
		else # If not injected
			echo "Not injected"
			not_injected="$not_injected $svc"
		fi
	else
		echo "Not injected"
		not_injected="$not_injected $svc"
	fi
done

# {{{1 Report results
echo "#####################"
echo "# Reporting Results #"
echo "#####################"

if [ ! -z "$not_injected" ]; then
	echo "Error: Service(s) not injected: $not_injected"
	exit 1
else
	echo "All services injected"
	exit 0
fi

