#!/bin/bash

set -eu

PROG_DIR=$(dirname $(realpath "$0"))
CONFIG_DIR="${PROG_DIR}/../salt-run/conf/"

# Change to rpi-vpn directory bc paths in conf (that aren't prepended with root_dir) are relative to current directory
cd "${PROG_DIR}/../"

salt-ssh --config-dir="$CONFIG_DIR" "$@"
