#!/usr/bin/env bash
# Installs NPM dependencies, starts MongoDB, and starts the server.
run() {
    set -x
    prog_dir=$(realpath $(dirname "$0"))
    server_dir="{{ pillar.wallet_service.install_dir }}/server"

    die() {
	   echo "Error: $@" >&2
	   exit 1
    }

    check() {
	   if [ "$?" -ne 0 ]; then
		  die "$@"
	   fi
    }

    # Change to server directory
    cd "$server_dir"
    check "Failed to change to server directory"

    # export NODE_ENV=production

    # export APP_API_PORT={{ pillar.wallet_service.api_server.port }}
    # export APP_DB_URI={{ pillar.wallet_service.mongo.uri }}

    # We pass the index.js file to stdin bc the prom-client NodeJS library
    # needs some sort of stdin to work: https://github.com/siimon/prom-client/issues/391
    # Yea, it's really weird.
    # exec node "$server_dir/index.js" < "$server_dir/index.js"

    exec docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f {{ pillar.wallet_service.docker_compose_env_file }} up --build
}

run 2>&1
