#!/usr/bin/env bash
exec chpst -u {{ pillar.prometheus.user }}:{{ pillar.prometheus.group }}:{{ pillar.docker.group }} docker run \
	-it \
	--rm \
	--net host \
	--name {{ pillar.pushgateway.docker_container_name }} \
	-p {{ pillar.pushgateway.port }}:{{ pillar.pushgateway.port }} \
	{{ pillar.pushgateway.docker_image }}
