#!/bin/sh

# Add $ARGS for more arguments
[ -f ./conf ] && . ./conf

: ${CONF_FILE:=/etc/alertmanager.yml}
: ${CONF_FLAG:=--config.file=$CONF_FILE}
: ${WRKDIR:=/var/lib/alertmanager}

cd "$WRKDIR"

set -x
exec chpst -u {{ pillar.alertmanager.user }}:{{ pillar.alertmanager.group }} alertmanager ${CONF_FLAG} ${ARGS} 2>&1
