base:
  '*':
    - system-config
    - hostname
    - zsh
    - docker
    - users
    - crond
    - syslog
    - vsv
    - email
    - email-secret
    - caddy
    - caddy-secret
    - prometheus
    - prometheus-secret
    - alertmanager
    - node-exporter
    - grafana 
    - void-scripts
    - znc-secret
    - znc
    - factorio
    - factorio-secret
    - backup
    - backup-secret
    - public-www
