base:
  '*':
    - system-config
    - zsh
    - users
    - crond
    - syslog
    - vsv
    - email
    - email-secret
    - prometheus
    - alertmanager
    - caddy
    - caddy-secret
    - grafana # Must come after caddy, reverse proxy setup requires caddy
    - void-scripts
    - znc-secret
    - znc
    - factorio
    - factorio-secret
    - backup
    - backup-secret
    - public-www
