base:
  '*':
    - salt-config
    - salt-dir-perms
    - srv-dir-perms
    - syslog
    - sshd-config
    - sudo-no-password
    - users
    - crond
    - motd
    - neovim
    - zsh
    - git
    - vsv
    - lnav
    - python
    - scripts-repo
    - void-scripts
    - znc-secret
    - znc
    - funkyboy-website
    - file-modes-website
    - noahhuppert-website
